name: keiser_metrics_connection
description: "Dart package for Keiser Metrics to handle both websockets and rest calls."
version: 0.7.3
repository: https://github.com/KeiserCorp/Keiser.Metrics.Connection.Dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  enum_to_string: ^2.0.1
  jwt_decoder: ^2.0.1
  retry: ^3.1.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^3.0.0
  test: ^1.24.9
