name: keiser_metrics_connection
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ">=4.0.1 <5.0.0"
  jwt_decoder: ^2.0.1
  retry: ^3.1.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
